spring.application.name=tour-guide
server.port=8081
logging.level.com.openclassrooms.tourguide=DEBUG

# proximity buffer value (in miles)
reward.default-proximity-buffer=10
reward.attraction-proximity-range=200

# TripPricer API configuration
trip.pricer.api.key=test-server-api-key
